### ISSUE TITLE
File not moving from processing to archive directory

### ISSUE THREAD

**Issue by christomecki** [KensoBI/gomxml-kafka#1]
1. I placed the `.xml` file into the `/processing` directory
2. The `gomxml-producer` console printed the message `Reading file ....`
3. However, my file disappeared from the `/processing` directory and ***did not appear in the `/archive` directory***.

> New data showed up in my DB, so it's not an issue of file parsing or Kafka.

This is the `docker-compose` configuration for `goxml-producer`:
```yml
gomxml-producer:
    container_name: gomxml-producer
    image: kensobi/gomxml-producer
    build:
      context: .
      dockerfile: producer.Dockerfile
    restart: always
    volumes:
      - ./processing:/processing
      - ./archive:/archive
    environment:
      Kafka__ProducerSettings__BootstrapServers: kafka:29092
      Kafka__Topic: dev.kenso.gom.xml
      Kafka__SchemaRegistries: http://schema-registry:8081
      Kafka__NumPartitions: 2
      Kafka__ReplicationFactor: 1
```

> I believe the issue may be related to this line: https://github.com/KensoBI/gomxml-kafka/blob/4bd06e9a1d663636f6ae7661ed36362262cd2631/Kenso.Services.Gom.XmlProducer/appsettings.json#L23
> Changing the value to `/archive` may resolve the issue.
